### ISSUE TITLE
Canal Davifo não possui conteúdos.

### ISSUE THREAD

**Issue by viktorleite** [carolsoaressantos/videos-pt.br-tecnologia#176]
O canal do [Davifo](https://www.youtube.com/c/GameLabLive/videos) da seção [Games](https://github.com/lucasmontano/youtube-br-desenvolvimento/blob/master/README.md#games-video_game) não possui conteúdos.

**Comment by lucasgomide** [comment]
fica a vontade para criar uma PR removendo o canal, @viktorleite
